sudo: required
services:
    - docker

before_install:
    - docker build -t ashishlakra13/reach-test -f ./client/Dockerfile.dev

script:
    - docker run -e CI=true ashishlakra13/react-test npm test 


after_success:
    - docker build -t ashishlakra13/multi-client ./client
    - docker build -t ashishlakra13/multi-nginx ./nginx
    - docker build -t ashishlakra13/multi-server ./server
    - docker build -t ashishlakra13/multi-worker ./worker
    