sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t ashishlakra13/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ashishlakra13/react-test npm test 


after_success:
    - docker build -t ashishlakra13/multi-client ./client
    - docker build -t ashishlakra13/multi-nginx ./nginx
    - docker build -t ashishlakra13/multi-server ./server
    - docker build -t ashishlakra13/multi-worker ./worker
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push ashishlakra13/multi-client
    - docker push ashishlakra13/multi-nginx
    - docker push ashishlakra13/multi-server
    - docker push ashishlakra13/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-901168954635
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
